### ISSUE TITLE
Feedback before Code Review 2

### ISSUE THREAD

**Issue by adrhill** [e-strauss/JML_XAI_Project#28]
Hi all,

here's some quick feedback before the second code review session next week.
I'm opening this as a single issue to not spam your repository.

### Documentation
* Please describe in the README what the repo is about and that it is part of course work at TU Berlin
* Please build a doc page until code review session 2 and include a usage example

### Code
* Good job on adding compat entries for all of your dependencies!
* It's good practice to include all of your source files, all of your dependencies and all of your exports in your "main file" `src/JML_XAI_Project.jl`. An example is given [here](https://adrianhill.de/julia-ml-course/write/#organizing_dependencies_source_files_and_exports).
You don't need to add more modules inside of your package.
* Your `LIME` struct could use a docstring
* Docstrings need to be written directly above methods and structs, without a newline (here in L36):
https://github.com/e-strauss/JML_XAI_Project/blob/4c4c11cf4e2d3063461bb72393fc6b41b83a3a53/src/Lime-base.jl#L29-L40

**Comment by e-strauss** [comment]
thanks @adrhill , we will look into that.

I have question regarding the unregistered LARS algorithm package we depend on. I looked into other lasso path packages, but they result in a different Coefficient - matrix, which is not suitable from my perspective. So we would stick to the LARS repo for now. I actually I needed to create my own fork of the repo, fix some function renaming to make julia 1.10 compatible...

**Comment by adrhill** [comment]
> So we would stick to the LARS repo for now.

Sounds good!

> I actually I needed to create my own fork of the repo, fix some function renaming to make julia 1.10 compatible...

Bonus points if you make a PR to the original repo with your fixes! ;)
You can run CI on the latest Julia release (currently 1.10) by updating [these lines in LARS.jl](https://github.com/simonster/LARS.jl/blob/5ae98cc1f86875efc461723af904f70499e27df3/.github/workflows/CI.yml#L15-L17
) to: 
```yml
- '1.0'
- '1.6'
- '1' # latest release
```

However, it looks like a similar PR might already exist: https://github.com/simonster/LARS.jl/pull/10

**Comment by e-strauss** [comment]
thanks - fixed in #51 & #61
