### ISSUE TITLE
Feedback for Code Review Session 2

### ISSUE THREAD

**Issue by cedric-len** [e-strauss/JML_XAI_Project#45]
### General

- Add the `.DS_STORE` file to the gitignore
- Add the missing compat entries to `Project.toml`
- Add the remaining authors to `Project.toml`

### Documentation

- In the README the following line doesn't work: `using JML_XAI_PROJECT`
I think it needs to be `using JML_XAI_Project`
- In the documentation in Getting Started > LIME you use a `include` statement. This only works when having access to the file
- Also it would to add some blank lines to some of the docstrings, else everything is displayed in the same line (see: https://e-strauss.github.io/JML_XAI_Project/dev/api/#JML_XAI_Project.weighted_data-Tuple{Any,%20Any,%20Any})

### Code

- I would suggest moving every import and export to the main project file.
Do the same for the tests: Move everything to `runtests.jl`
- There a few functions that are missing type annotations, e.g.
`function data_labels(image, fudged_image, segments, classifier_fn, num_samples, batch_size=10)`
- Maybe add a utility function for retrieving the label
`argmax(expl.output[:,1]) - 1`

**Comment by e-strauss** [comment]
thanks - fixed in #61  #59
